apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}