services:
  mongodb:
    image: mongo:7.0
    ports: 
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db

  fetcher:
    build:
      context: .
      dockerfile: build/Dockerfile.trainer
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PYTHONPATH=/app
    restart: "no"
    command: ["python", "scripts/store_database.py"]
    
  trainer:
    build:
      context: .
      dockerfile: build/Dockerfile.trainer
    depends_on:
      - fetcher
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PYTHONPATH=/app
    restart: "no"
    volumes:
      - ./models:/app/models

  api:
    build:
      context: .
      dockerfile: build/Dockerfile.api
    depends_on:
      - trainer
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PYTHONPATH=/app
    restart: always
    volumes:
      - ./models:/app/models


volumes:
  mongodb_data: