apiVersion: apps/v1
kind: Deployment
metadata:
  name: dota2metalab-api
  namespace: dota2metalab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dota2metalab-api
  template:
    metadata:
      labels:
        app: dota2metalab-api
    spec:
      containers:
        - name: api
          image: rinavillaruz/dota2metalab-api:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017
            - name: PYTHONPATH
              value: /app
          volumeMounts:
            - mountPath: /app/models
              name: models-storage
      volumes:
        - name: models-storage
          persistentVolumeClaim:
            claimName: models-pvc