apiVersion: batch/v1
kind: Job
metadata:
  name: dota2metalab-fetcher
  namespace: dota2metalab
spec:
  backoffLimit: 3 #defaults to 6
  template:
    spec:
      containers:
        - name: fetcher
          image: dota2metalab-fetcher:latest
          command: ["python", "scripts/store_database.py"]
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017
            - name: PYTHONPATH
              value: /app
      restartPolicy: Never