apiVersion: batch/v1
kind: Job
metadata:
  name: dota2metalab-trainer
  namespace: dota2metalab
spec:
  backoffLimit: 3 #defaults to 6
  template:
    spec:
      containers:
        - name: trainer
          image: dota2metalab-trainer:latest
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017
            - name: PYTHONPATH
              value: /app
          volumeMounts:
            - name: models-storage
              mountPath: /app/models
      volumes:
        - name: models-storage
          persistentVolumeClaim:
            claimName: models-pvc
      restartPolicy: Never