# Global settings
global:
  namespace: dota2metalab-dev

# Image settings — GitHub Actions will update this tag with SHA
image:
  tag: bd21a8e6479465dc72db2ef1df900b96646a0702

# MongoDB settings
mongodb:
  persistence:
    size: 2Gi
    storageClassName: standard

# Models storage
models:
  persistence:
    size: 500Mi
    storageClassName: standard