# Global settings
global:
  namespace: dota2metalab-dev

# Image settings — GitHub Actions will update this tag with SHA
image:
  tag: b972588baae3b753f2b79eb1e6da429bab1f115f

# MongoDB settings
mongodb:
  persistence:
    size: 2Gi
    storageClassName: standard

# Models storage
models:
  persistence:
    size: 500Mi
    storageClassName: standard